# Generated by Django 6.0.4 on 2026-05-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='cost',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Costo'),
        ),
        migrations.AddField(
            model_name='place',
            name='history',
            field=models.TextField(blank=True, null=True, verbose_name='Historia'),
        ),
        migrations.AddField(
            model_name='place',
            name='importance',
            field=models.TextField(blank=True, null=True, verbose_name='Importancia turística'),
        ),
        migrations.AddField(
            model_name='place',
            name='recommendations',
            field=models.TextField(blank=True, null=True, verbose_name='Recomendaciones'),
        ),
        migrations.AddField(
            model_name='place',
            name='schedule',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Horario'),
        ),
        migrations.AddField(
            model_name='place',
            name='tips',
            field=models.TextField(blank=True, null=True, verbose_name='Consejos'),
        ),
    ]
