# Generated by Django 6.0.4 on 2026-05-08 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_cost_place_history_place_importance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='is_visited',
        ),
        migrations.RemoveField(
            model_name='place',
            name='visited_date',
        ),
    ]
