# Generated by Django 6.0.4 on 2026-05-13 15:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_place_is_visited_remove_place_visited_date'),
        ('routes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Route',
                'verbose_name_plural': 'Custom Routes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomRoutePlace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('custom_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_places', to='routes.customroute')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_route_places', to='places.place')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('custom_route', 'place')},
            },
        ),
    ]
