# Generated by Django 6.0.4 on 2026-05-12 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('visited_place', 'Lugar visitado'), ('favorite_place', 'Lugar agregado a favoritos'), ('custom_route', 'Ruta personalizada creada'), ('completed_route', 'Ruta completada'), ('chatbot_use', 'Uso del chatbot'), ('ar_experience', 'Experiencia de realidad aumentada')], max_length=50)),
                ('points', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=255)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'action', 'object_id'), name='unique_user_action_object_points')],
            },
        ),
    ]
